services:
  nginx: 
    image: nginx:1.27.0
    container_name: server
    volumes:
      - ./nginx.conf:/etc/nginx/templates/default.conf.template
    environment:
      SERVER_FRONTEND_URL: 'http://calendar-frontend:4000'
      SERVER_BACKEND_URL: 'http://calendar-backend:5000'
    ports:
      - 80:80
    depends_on:
      - calendar-frontend
      - calendar-backend
    networks:
      - public

  postgres:
    container_name: postgres
    image: postgres:16.3
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432'
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - calendar-database:/var/lib/postgresql/data
    networks:
      - private

  calendar-backend:
    container_name: backend
    image: calendar-backend:latest
    command: >
      sh -c "npm run migrate && 
             npm run pm2"
    environment:
      NODE_ENV: development
      PORT: 5000
      DATABASE_CLIENT: postgresql
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_NAME: personal_calendar
      DATABASE_USER: postgres
      DATABASE_USER_PASSWORD: postgres
      DATABASE_ENABLE_SSL: false
      TEST_DATABASE_HOST: postgres
      TEST_DATABASE_PORT: 5432
      TEST_DATABASE_NAME: personal_calendar_test
      TEST_DATABASE_USER: postgres
      TEST_DATABASE_USER_PASSWORD: postgres
      TEST_DATABASE_ENABLE_SSL: false
      JWT_SECRET: obxJKoasd1fa5asdf6FG7yhsWg53vxgtr98vhqew98UH38s
      JWT_EXPIRE: 7d
    depends_on:
      - postgres
    ports:
      - '5000'
    networks:
      - public
      - private

  calendar-frontend:
    container_name: frontend
    image: calendar-frontend:latest
    environment:
      FRONT_END_PORT: 4000
    ports:
      - '4000'
    networks:
      - public

networks:
  public:
  private:

volumes:
  calendar-database:
